### ISSUE TITLE
8.51 Issue

### ISSUE THREAD

**Issue by RyanZuZi** [ectrc/snow#4] opened 2023-12-20 00:36 UTC
I set everything up correctly but still not getting logged in. I'm on the latest Commit. Any suggestions?

C:\Users\Rzals\Desktop\snow-master>go build

C:\Users\Rzals\Desktop\snow-master>snow.exe
Fortnite Assets from https://fortnite-api.com
Discord bot is ready
Preloaded 2050 cosmetics with 1066 display assets ( 31.151373465809467 % ) coverage
Generated new random storefront
Generated playlist images
Gave everything to god
Listening on http://127.0.0.1:3000
(POST) (404) (           0s) /datarouter/api/v1/public/data
(POST) (200) (      511.1µs) /account/api/oauth/token
(POST) (200) (      576.8µs) /account/api/oauth/token
(POST) (200) (      503.2µs) /account/api/oauth/token
(POST) (200) (      558.9µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      526.4µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      521.1µs) /account/api/oauth/token
(POST) (200) (      491.2µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      540.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      598.3µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      568.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      530.9µs) /account/api/oauth/token
(POST) (200) (      854.4µs) /account/api/oauth/token
(POST) (200) (      501.6µs) /account/api/oauth/token
(POST) (200) (      537.8µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      658.4µs) /account/api/oauth/token
(POST) (200) (      534.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      490.7µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      520.1µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      536.3µs) /account/api/oauth/token
(POST) (200) (      836.7µs) /account/api/oauth/token
(POST) (200) (      537.8µs) /account/api/oauth/token
(POST) (200) (      588.5µs) /account/api/oauth/token
(POST) (200) (      536.4µs) /account/api/oauth/token
(POST) (200) (      593.8µs) /account/api/oauth/token
(POST) (200) (      483.8µs) /account/api/oauth/token
(POST) (200) (      791.2µs) /account/api/oauth/token
(POST) (200) (      559.9µs) /account/api/oauth/token
(POST) (200) (      545.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      569.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (     1.0017ms) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      525.2µs) /account/api/oauth/token
(POST) (200) (      547.3µs) /account/api/oauth/token
(POST) (200) (      545.2µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (     1.0017ms) /account/api/oauth/token
(POST) (200) (      475.1µs) /account/api/oauth/token
(POST) (200) (      662.6µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      529.4µs) /account/api/oauth/token
(POST) (200) (      506.4µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      511.7µs) /account/api/oauth/token
(POST) (200) (      608.8µs) /account/api/oauth/token
(POST) (200) (      128.2µs) /account/api/oauth/token
(POST) (200) (      688.4µs) /account/api/oauth/token
(POST) (200) (      636.1µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (        628µs) /account/api/oauth/token
(POST) (200) (      707.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      726.6µs) /account/api/oauth/token
(POST) (200) (      513.8µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (        499µs) /account/api/oauth/token
(POST) (200) (      667.6µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (        576µs) /account/api/oauth/token
(POST) (200) (        594µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      656.7µs) /account/api/oauth/token
(POST) (200) (      535.1µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (429) (      590.7µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      508.6µs) /account/api/oauth/token
(POST) (200) (      513.2µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (        543µs) /account/api/oauth/token
(POST) (200) (      570.5µs) /account/api/oauth/token
(POST) (200) (      542.8µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      550.4µs) /account/api/oauth/token
(POST) (200) (      524.7µs) /account/api/oauth/token
(POST) (200) (      626.2µs) /account/api/oauth/token
(POST) (200) (      564.7µs) /account/api/oauth/token
(POST) (200) (      524.9µs) /account/api/oauth/token
(POST) (200) (      526.4µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      580.7µs) /account/api/oauth/token
(POST) (200) (      802.4µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      644.8µs) /account/api/oauth/token
(POST) (200) (      532.1µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      657.9µs) /account/api/oauth/token
(POST) (200) (      734.6µs) /account/api/oauth/token
(POST) (200) (      562.5µs) /account/api/oauth/token
(POST) (200) (        541µs) /account/api/oauth/token
(POST) (200) (      516.6µs) /account/api/oauth/token
(POST) (200) (      541.1µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      508.8µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (        548µs) /account/api/oauth/token
(POST) (200) (      537.1µs) /account/api/oauth/token
(POST) (200) (      576.4µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      590.7µs) /account/api/oauth/token
(POST) (200) (      565.2µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      619.3µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      511.6µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      538.2µs) /account/api/oauth/token
(POST) (200) (      567.3µs) /account/api/oauth/token
(POST) (200) (      477.3µs) /account/api/oauth/token
(POST) (200) (      490.1µs) /account/api/oauth/token
(POST) (200) (      629.3µs) /account/api/oauth/token
(POST) (200) (      579.3µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      661.4µs) /account/api/oauth/token
(POST) (200) (      640.9µs) /account/api/oauth/token
(POST) (200) (      550.5µs) /account/api/oauth/token
(POST) (200) (      501.7µs) /account/api/oauth/token
(POST) (200) (      590.9µs) /account/api/oauth/token
(POST) (200) (      502.6µs) /account/api/oauth/token
(POST) (200) (        555µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      812.8µs) /account/api/oauth/token
(POST) (200) (      499.6µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      570.9µs) /account/api/oauth/token
(POST) (200) (        489µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      489.5µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      925.6µs) /account/api/oauth/token
(POST) (200) (      487.4µs) /account/api/oauth/token
(POST) (200) (      605.6µs) /account/api/oauth/token
(POST) (200) (      527.3µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      737.4µs) /account/api/oauth/token
(POST) (200) (      733.9µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (        582µs) /account/api/oauth/token
(POST) (200) (      655.2µs) /account/api/oauth/token
(POST) (200) (      615.8µs) /account/api/oauth/token
(POST) (200) (      491.2µs) /account/api/oauth/token
(POST) (200) (      517.7µs) /account/api/oauth/token
(POST) (200) (      536.9µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      542.6µs) /account/api/oauth/token
(POST) (200) (      533.8µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      544.8µs) /account/api/oauth/token
(POST) (200) (      550.6µs) /account/api/oauth/token
(POST) (200) (      567.2µs) /account/api/oauth/token
(POST) (200) (      494.5µs) /account/api/oauth/token
(POST) (200) (      585.7µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      530.7µs) /account/api/oauth/token
(POST) (200) (           0s) /account/api/oauth/token
(POST) (200) (      542.4µs) /account/api/oauth/token
(POST) (200) (      562.6µs) /account/api/oauth/token
(POST) (429) (      584.7µs) /account/api/oauth/token

**Comment by ectrc** [comment] 2023-12-24 16:15
# Known Issue
Still am trying to figure out why. There is a pull request, try and use his fix and reply if it works.

**Comment by RyanZuZi** [comment] 2023-12-25 21:49
I downloaded and tried using their fix. Problem is I can't test it because now it won't build.

C:\Users\Rzals\Desktop\Snow>go build
# github.com/ectrc/snow/handlers
handlers\auth.go:30:11: syntax error: unexpected :, expected {
handlers\auth.go:35:18: syntax error: unexpected :, expected := or = or comma
handlers\auth.go:48:16: syntax error: unexpected :, expected := or = or comma
handlers\auth.go:49:9: syntax error: missing statement after label
handlers\auth.go:69:11: syntax error: missing statement after label
handlers\auth.go:119:9: syntax error: missing statement after label
handlers\auth.go:156:9: syntax error: missing statement after label
handlers\auth.go:178:9: syntax error: missing statement after label
handlers\auth.go:203:11: syntax error: missing statement after label
handlers\auth.go:216:13: syntax error: missing statement after label
handlers\auth.go:216:13: too many errors

C:\Users\Rzals\Desktop\Snow>

**Comment by RyanZuZi** [comment] 2023-12-26 03:37
Issue is now fixed in https://github.com/ectrc/snow/pull/5

**Comment by ectrc** [comment] 2023-12-26 03:53
@RyanZuZi Use the latest commit and see if it fixes the issue as I have still dont know about the cause

**Comment by 2vb** [comment] 2023-12-26 04:05
Just tried latest commit and issue looks to be fixed on 8.51

**Closed** 2023-12-26 04:08 UTC
